spring:
    application:
        name: Spring Server
    datasource:
        url: jdbc:postgresql://localhost:5432/server
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
